In [6]:
#load data set and handle missing values if any
from scipy.io import arff
import pandas as pd
import numpy as np

data = arff.loadarff('EEG_Eye_State.arff')
eyeData = pd.DataFrame(data[0])

eyeData = eyeData.replace('[?]', np.nan , regex = True)
eyeData = eyeData.dropna()
eyeData

AF3       F7       F3      FC5       T7       P7       O1       O2  \
0      4329.23  4009.23  4289.23  4148.21  4350.26  4586.15  4096.92  4641.03   
1      4324.62  4004.62  4293.85  4148.72  4342.05  4586.67  4097.44  4638.97   
2      4327.69  4006.67  4295.38  4156.41  4336.92  4583.59  4096.92  4630.26   
3      4328.72  4011.79  4296.41  4155.90  4343.59  4582.56  4097.44  4630.77   
4      4326.15  4011.79  4292.31  4151.28  4347.69  4586.67  4095.90  4627.69   
5      4321.03  4004.62  4284.10  4153.33  4345.64  4587.18  4093.33  4616.92   
6      4319.49  4001.03  4280.51  4151.79  4343.59  4584.62  4089.74  4615.90   
7      4325.64  4006.67  4278.46  4143.08  4344.10  4583.08  4087.18  4614.87   
8      4326.15  4010.77  4276.41  4139.49  4345.13  4584.10  4091.28  4608.21   
9      4326.15  4011.28  4276.92  4142.05  4344.10  4582.56  4092.82  4608.72   
10     4326.15  4010.77  4272.82  4143.08  4342.56  4579.49  4087.69  4615.90   
11     4316.92  4002.56  4259.49  4135.90  4339.49  4581.54  4086.15  4615.38   
12     4308.21  3993.33  4247.69  4124.62  4335.90  4584.62  4089.74  4610.26   
13     4308.21  3998.46  4251.79  4122.56  4338.46  4584.62  4091.28  4616.92   
14     4312.82  4006.15  4260.51  4127.69  4341.03  4586.15  4089.74  4628.72   
15     4313.85  4003.59  4255.90  4127.69  4337.95  4586.15  4091.28  4627.69   
16     4306.67  3997.95  4247.18  4122.56  4336.92  4584.10  4094.36  4620.51   
17     4303.59  3996.41  4249.23  4122.05  4341.03  4584.10  4090.77  4616.41   
18     4312.31  4000.00  4255.90  4124.10  4342.05  4586.67  4085.64  4610.77   
19     4315.90  4003.59  4257.44  4122.56  4341.54  4588.21  4088.21  4607.18   
20     4314.36  4005.64  4259.49  4123.59  4345.13  4588.21  4092.31  4612.82   
21     4324.62  4012.82  4263.08  4132.31  4343.08  4587.18  4091.79  4617.95   
22     4331.28  4024.10  4266.15  4140.00  4336.41  4585.64  4089.74  4617.95   
23     4326.67  4020.00  4264.10  4137.44  4334.36  4586.15  4088.21  4621.54   
24     4321.54  4007.69  4260.00  4132.31  4340.00  4585.64  4087.18  4630.26   
25     4317.44  4007.69  4257.44  4128.72  4343.59  4585.13  4088.21  4638.97   
26     4311.79  4007.18  4250.77  4125.13  4336.41  4587.18  4087.69  4634.36   
27     4308.72  4000.00  4245.13  4121.54  4329.23  4585.64  4086.67  4617.44   
28     4308.21  4002.05  4252.82  4122.56  4332.82  4582.56  4087.69  4610.77   
29     4311.28  4011.28  4265.13  4130.26  4339.49  4583.59  4089.74  4616.41   
...        ...      ...      ...      ...      ...      ...      ...      ...   
14950  4330.26  4036.41  4282.05  4141.03  4341.03  4614.87  4068.21  4621.54   
14951  4325.64  4037.44  4278.97  4145.13  4335.90  4609.74  4066.67  4616.92   
14952  4326.67  4038.97  4280.51  4148.72  4334.36  4604.10  4066.67  4620.51   
14953  4327.69  4038.46  4280.51  4146.67  4340.00  4609.23  4071.79  4628.21   
14954  4328.72  4037.44  4279.49  4149.23  4342.05  4616.41  4074.36  4627.18   
14955  4328.21  4036.92  4281.03  4153.33  4335.90  4616.41  4075.38  4623.59   
14956  4322.05  4034.87  4280.00  4151.79  4332.31  4612.82  4076.92  4624.62   
14957  4315.90  4031.79  4275.38  4149.23  4337.44  4614.36  4077.44  4624.62   
14958  4315.90  4027.69  4275.90  4148.72  4338.97  4620.51  4077.95  4628.72   
14959  4312.31  4022.05  4278.46  4149.23  4336.92  4623.59  4081.54  4639.49   
14960  4304.10  4016.92  4273.85  4145.13  4340.00  4623.59  4084.10  4646.67   
14961  4303.08  4016.92  4270.77  4138.97  4342.05  4621.54  4082.56  4645.64   
14962  4304.62  4018.46  4272.31  4139.49  4340.00  4619.49  4082.56  4637.95   
14963  4301.03  4013.85  4268.72  4140.00  4341.03  4617.44  4082.05  4626.15   
14964  4300.00  4009.23  4263.59  4138.46  4342.56  4617.95  4083.59  4623.08   
14965  4302.56  4008.72  4265.13  4138.97  4336.41  4618.46  4088.72  4630.77   
14966  4297.95  4006.15  4266.15  4136.92  4330.77  4615.90  4088.21  4631.79   
14967  4293.85  4005.13  4262.56  4134.87 

In [7]:
dataArray = np.array(eyeData)

In [8]:
data = dataArray[:,0:14]
data

array([[4329.23, 4009.23, 4289.23, ..., 4280.51, 4635.9, 4393.85],
       [4324.62, 4004.62, 4293.85, ..., 4279.49, 4632.82, 4384.1],
       [4327.69, 4006.67, 4295.38, ..., 4282.05, 4628.72, 4389.23],
       ...,
       [4277.44, 3990.77, 4246.67, ..., 4257.95, 4591.79, 4339.49],
       [4284.62, 3991.79, 4251.28, ..., 4267.18, 4596.41, 4350.77],
       [4287.69, 3997.44, 4260.0, ..., 4274.36, 4597.95, 4350.77]],
      dtype=object)

In [9]:
target = dataArray[:,14]
target

array([b'0', b'0', b'0', ..., b'1', b'1', b'1'], dtype=object)

In [10]:
data.shape

(14980, 14)

In [11]:
reshapedData = data.reshape(14980,14,1)
reshapedData.shape

(14980, 14, 1)

In [12]:
target.shape

(14980,)

In [13]:
#split data into train and test
split1 = 0.8 * len(dataArray)
split1 = int(split1)

xtrain = reshapedData[0:split1,0:14]
ytrain = target[0:split1]
xtest = reshapedData[split1 + 1:len(dataArray),0:14]
ytest = target[split1 + 1:len(dataArray)]

In [14]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

#model = Sequential()
#model.add(LSTM((1),batch_input_shape = (14980,14,1), return_sequences = False))
#model.compile(loss = 'mean_absolute_error', optimizer = 'adam', metrics = ['accuracy'])
#model1 = model.fit(xtrain,ytrain,epochs = 300 )

In [15]:
#model.summary()

In [35]:
model1 = Sequential()
model1.add(LSTM(1, input_shape=(14,1)))
model1.add(Dense(1, activation='linear'))
# compile model
model1.compile(loss ='mean_absolute_error', optimizer='adam', metrics = ['accuracy'])


In [36]:
model1.fit(xtrain, ytrain, epochs = 50, shuffle = False, verbose=1)


Epoch 1/50
11984/11984 [==============================] - 3s 231us/step - loss: 0.5402 - acc: 0.4624
Epoch 2/50
11984/11984 [==============================] - 2s 178us/step - loss: 0.5378 - acc: 0.4624
Epoch 3/50
11984/11984 [==============================] - 2s 188us/step - loss: 0.5356 - acc: 0.4624
Epoch 4/50
11984/11984 [==============================] - 2s 182us/step - loss: 0.5334 - acc: 0.4624
Epoch 5/50
11984/11984 [==============================] - 2s 188us/step - loss: 0.5313 - acc: 0.4624
Epoch 6/50
11984/11984 [==============================] - 2s 183us/step - loss: 0.5291 - acc: 0.4624
Epoch 7/50
11984/11984 [==============================] - 2s 187us/step - loss: 0.5269 - acc: 0.4624
Epoch 8/50
11984/11984 [==============================] - 2s 179us/step - loss: 0.5247 - acc: 0.4624
Epoch 9/50
11984/11984 [==============================] - 2s 183us/step - loss: 0.5225 - acc: 0.4624
Epoch 10/50
11984/11984 [==============================] - 2s 168us/step - loss: 0.5203 - a

In [48]:
results = model1.predict(xtest)
results.astype(int)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [49]:
#import matplotlib.pyplot as plt
#plt.scatter(2995,results,c = 'r')
#plt.scatter(2995,ytest, c = 'g')
#plt.show()
ytest.shape

(2995,)

In [50]:
#Test model1
xtest1 = xtest[0:9,:]
ytest1 = ytest[10,]
model1.predict(xtest1).astype(int)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [52]:
model2 = Sequential()
model2.add(LSTM(10, input_shape=(14,1)))
model2.add(Dense(1, activation='linear'))
# compile model
model2.compile(loss ='mean_absolute_error', optimizer='adam', metrics = ['accuracy'])


In [53]:
model2.fit(xtrain, ytrain, epochs = 50, shuffle = False, verbose=1)

Epoch 1/50
11984/11984 [==============================] - 5s 416us/step - loss: 0.4938 - acc: 0.5376
Epoch 2/50
11984/11984 [==============================] - 4s 317us/step - loss: 0.4791 - acc: 0.5376
Epoch 3/50
11984/11984 [==============================] - 3s 285us/step - loss: 0.4772 - acc: 0.5376
Epoch 4/50
11984/11984 [==============================] - 3s 273us/step - loss: 0.4775 - acc: 0.5376
Epoch 5/50
11984/11984 [==============================] - 3s 264us/step - loss: 0.4791 - acc: 0.5376
Epoch 6/50
11984/11984 [==============================] - 3s 288us/step - loss: 0.4767 - acc: 0.5376
Epoch 7/50
11984/11984 [==============================] - 4s 297us/step - loss: 0.4791 - acc: 0.5376
Epoch 8/50
11984/11984 [==============================] - 3s 282us/step - loss: 0.4772 - acc: 0.5376
Epoch 9/50
11984/11984 [==============================] - 3s 273us/step - loss: 0.4775 - acc: 0.5376
Epoch 10/50
11984/11984 [==============================] - 3s 270us/step - loss: 0.4791 - a

In [55]:
results2 = model2.predict(xtest)
results2.astype(int)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [57]:
model1.predict(xtest).astype(int)

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])